//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstMitNet472
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clubs
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime FoundingYear { get; set; }
        public long TransferBudget { get; set; }
        public int ArenaCapacity { get; set; }
        public string ArenaName { get; set; }
    }
}
